### PR TITLE
Adding Python 2.7.16

### PR DESCRIPTION
**Pull request by rklyne**
Changelog from Python 2.7.16 - https://raw.githubusercontent.com/python/cpython/v2.7.16/Misc/NEWS.d/2.7.16.rst

### CODE REVIEW

**Comment by rocky** [comment]
Thanks!

**Comment by rklyne** [comment]
No, no, thank you!

If you have time to put out a point release with this change I'd appreciate it. I had a CI build fail on the latest Python 2.7 because of a dependency chain `hypothesis` -> `uncompyle` -> `xdis`. This may be a common scenario?

**Comment by rocky** [comment]
Ok - thans for the information. I will try to do over the upcoming weekend. `

**Comment by rocky** [comment]
Ok. [Release 3.8.10 .should be out now on pypi](https://pypi.org/project/xdis/)  to cover this commit.

**Comment by rklyne** [comment]
Working like a charm. Thank you so much for taking the time

**Comment by rocky** [comment]
Good to have independent confirmation of the release. (I've messed up releases in the past)

**Pull request merged**
