### PR TITLE
Test tweaks

### PR DESCRIPTION
**Pull request by x746e**

### CODE REVIEW

**Comment by rocky** [comment]
Looks like this breaks Travis CI.

**Comment by x746e** [comment]
And that's expected and a good thing!  It seems that previously not all tests were run by CI.

**Comment by rocky** [comment]
Ok. But I can't accept this until the bug is fixed.

**Comment by rocky** [comment]
Rebase off of the current master to fix the failing test?

**Comment by x746e** [comment]
One other test is failing under pypy.  I'll look into it tomorrow.

**Comment by x746e** [comment]
BTW, under my distribution's ancient PyPy 2.2.1 there are a few more failing tests: https://gist.github.com/x746e/657573c3d02ae6355dfaf63cce1707d4.

**Comment by x746e** [comment]
`test_load_file` seems to fail because of difference between `co_flags` of code objects returned by `xdis.load.load_file` and `xdis.load.load_module`:

(Pdb) p co.co_flags                                                                                                                                                                                                                                                                      
256
(Pdb) p co2.co_flags                                                                                                                                                                                                                                                                     
0

**Comment by x746e** [comment]
Not sure why `co_flags` are `0x100`, I suspect it's equal to `PyCF_SOURCE_IS_UTF8` [1].

Moreover, it seems that the type of source string is influencing that flag (only on PyPy):

```shell
% pypy
Python 2.7.12 (aff251e54385, Nov 09 2016, 18:02:49)
[PyPy 5.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> compile('x = 1', 'hz', 'exec').co_flags
0
>>>> compile(u'x = 1', 'hz', 'exec').co_flags
256
>>>> 
% python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> compile('x = 1', 'hz', 'exec').co_flags
64
>>> compile(u'x = 1', 'hz', 'exec').co_flags
64
```

[1] https://bitbucket.org/pypy/pypy/src/aff251e543859ce4508159dd9f1a82a2f553de00/pypy/interpreter/astcompiler/consts.py?at=release-pypy2.7-v5.6.0&fileviewer=file-view-default

One way to fix the tests would be to change `xdis.load.load_file` to try first load read the file in `latin1` encoding.

**Comment by rocky** [comment]
I ask myself the question, is this a failure the xdis code or a failure in the test. It looks to me like a failure in the test when run with PyPy. If that's correct, then it is okay to fix the test as you suggest. 

I'd ask if possible to do this only when PyPy is used. 

And while on that topic, I'm not totally happy with the way we indicate versions for pypy using an extra parameter. But am not sure how to fix and don't have the time to either. 

Lastly, I am fine with having this work on PyPy 2.2.1; this library is about supporting different Python versions when it is practical.

**Comment by rocky** [comment]
Now conflicts need resolving.

**Comment by x746e** [comment]
A few tests added in https://github.com/rocky/python-xdis/pull/26 are failing under Python 3: https://gist.github.com/x746e/3320899785157181fea34613abb40e97.

@moagstar, could you take a look?

**Comment by moagstar** [comment]
I'll take a look

**Comment by moagstar** [comment]
Should be fixed with https://github.com/rocky/python-xdis/pull/30/commits/c4e899254b6418b51982097be2281ed6aae0ac30

**Comment by rocky** [comment]
Maybe try merging in master or rebasing it off of master?

**Comment by moagstar** [comment]
@rocky was you question aimed at me or @x746e ?

**Comment by rocky** [comment]
@moagstar Just wanted the conflict resolved so we could merge. I see that things are clean now, so I'll merge.

**Pull request merged**
