### PR TITLE
Python 3.11 - 3.13 Line number fixes

### PR DESCRIPTION
**Pull request by 2elli**
At some point line numbers for these versions were messed up, not sure exactly what happened. I have been trying to test more and across multiple versions so these issues don't arise again.

Fixes:
- Line number inaccuracies for 3.11-3.13.
- Instructions that index into the co_localsplusnames table were not being parsed correctly. Previously we recreated the table by adding `varnames` to `cells` without resolving duplicate items that may occur in both tables.

### CODE REVIEW

**Comment by 2elli** [comment]
@rocky From my understanding, there are some tests that cover code object members like the line tables in `pytest/test_std.py`, but they need to be updated for newer versions. Should these be updated and integrated into the normal `make check` or `make check-full`? 

I have mostly been testing manually and with `make check` / `make check-full`. The make tests seem to not cover some cases like the line table. If this is a misunderstanding of how xdis tests should be ran on my part, some guidance on how to better test would be greatly appreciated.

**Comment by rocky** [comment]
> @rocky From my understanding, there are some tests that cover code object members like the line tables in `pytest/test_std.py`, but they need to be updated for newer versions. Should these be updated

Yes, when I run the tests I see 

> pytest/test_std.py::test_findlabels SKIPPED (Python 3.10 and above doesn't have branches in this code)                                           [ 86%]

which seems clear enough what was up there. 


> and integrated into `make check` or `make check-full`?

Yes, please. 

> 
> I have mostly been testing manually and with `make check` / `make check-full`. The make tests seem to not cover some cases like the line table. If this is a misunderstanding of how xdis tests should be ran on my part, some guidance on how to better test would be greatly appreciated.

`make check and `make check-full` (or with `remake`) is how I run them too. 

Thanks for the PR and the work. Please give me a couple of days to get to this. Things have been a bit busy recently.

**Comment by rocky** [comment]
Looks very good. Thanks for doing this. 

"black" wants to reformat "bytecode.py", but I will do that after the merge. 

Sorry for the delay. I wanted to make sure I understood what's up here.

**Comment by 2elli** [comment]
Thanks @rocky!

**Pull request merged**
