### PR TITLE
Add details about GPL-2.0 license

### PR DESCRIPTION
**Pull request by toddrme2178**
Some files in the project have  GPL-2.0 license header, others have an MIT license header, and others have no license header at all.  This pull requests add the GPL-2.0 license text, changes the effective license of the project, and adds a document explaining the situation.  

I don't know the full story with the MIT-licensed files or who might have contributed code to the headerless files, so the safe approach is to keep the current license for all files as-is.  Files that will be re-licensed should have a header added to them mentioning the license.  If all code is re-licensed under GPL-2.0 or MIT, the other license file and `COPYING.txt` can be dropped.

### CODE REVIEW

**Comment by rocky** [comment]
Thanks.Will look at whenIcan.

**Comment by rocky** [comment]
Thanks for handling.

**Comment by toddrjen** [comment]
It looks like COPYING.txt isn't getting included in the pypi package.  I don't know how to fix that.  Would you be able to fix it?

**Comment by toddrme2178** [comment]
It looks like the COPYING.txt file isn't getting included in the pypi sources, but I don't know how to change that.  Would you be able to fix that?

**Comment by rocky** [comment]
Commit b271119 should address. There's another bug I found in xdis yesterday, so a release will occur not too far in the future.

**Pull request merged**
